### ISSUE TITLE
Unable to successfully execute a POST request after a correctly formatted a POST request is sent to the server.

### ISSUE THREAD

**Issue by OneNameMarty** [CSAllenISDClassroom/sudokuserver-e10-vapor#11]
After a POST request is sent to the server with the resource tags: /games?difficulty=easy
(The server does get the request as can be seen in the attached image)
The response contains an not found error.
```javascipt
{
    "error": true,
    "reason": "Not Found"
}
```
If you have any further questions relating to replication of this error or otherwise please feel free to reach out at jean-martin.vaneskahian@student.allenisd.or
![Screenshot_2021-10-11_23-46-22](https://user-images.githubusercontent.com/70408339/136893197-dd80e7c8-94e9-4ef5-bf20-a7f957906eb0.png)
g

**Comment by Noah0Chin** [comment]
Badrequest errors and refined POST Api fixed, there should now be a bad request error message for POST requests, resolved
