### ISSUE TITLE
Core dumped when I did Vapor run

### ISSUE THREAD

**Issue by SlickArrow0305** [CSAllenISDClassroom/sudokuserver-e10-vapor#12]
I executed a vapor run in the directory and it gave me a core dumped error telling me there was an illegal instruction

**Comment by elena-paul** [comment]
The same happened for me after vapor run (I got a 'core dumped' and 'illegal instruction' message)

**Comment by kittychesire7090** [comment]
There was also an error with not finding the cellsArray in scope.

**Comment by Noah0Chin** [comment]
cellsArray issue has been resolved, core dumped due to accidental push of a corrupted build, resolved
