### ISSUE TITLE
Errors After Vapor Run

### ISSUE THREAD

**Issue by elena-paul** [CSAllenISDClassroom/sudokuserver-e10-vapor#14]
So after I did vapor run, I got 4 errors: cellsArray is not in scope, string interpolation errors, warning that states that 'String(describing:)', is needed and that a default value is needed. Please let me know if you would like to clarify anything related to this issue at elena.paul@student.allenisd.org. Hope this helps.
![e10_VaporRunErrors](https://user-images.githubusercontent.com/89466022/138109581-f056816a-4bb2-45e0-a4d1-48d0abf17ea5.PNG)

**Comment by Triston42** [comment]
I have the same exact errors
![image](https://user-images.githubusercontent.com/70528821/138384843-1720fb93-bc99-40cb-aca0-639fb4ab50b8.png)

**Comment by Noah0Chin** [comment]
Accidental push of a build that didn't compile correctly, resolved
