### ISSUE TITLE
cellsArray not working in board.swift

### ISSUE THREAD

**Issue by AO298382** [CSAllenISDClassroom/sudokuserver-e10-vapor#15]
Tried running the server, but got an error regarding cellsArray in board.swift stating that cellsArray cannot be found in scope.

**Comment by kittychesire7090** [comment]
I also got a warning saying that the "string interpolation produces a debug description for an optional value".

**Comment by Noah0Chin** [comment]
There are currently many string interpolation issues due to forcefully printing out interpolated difficulty string? in throw Abort statement, will fix.

**Comment by Noah0Chin** [comment]
The cellsArray issue was due to an accidental push of a build that did not compile correctly, resolved
